good_places = ["Europe", "German", "France", "Janpan", "Tibet", "Califolia"]
print(good_places)
print("\n")
print(sorted(good_places))
print("\n")
print(good_places)
print("\n")
print(sorted(good_places, reverse = True))
print("\n")
print(good_places)
good_places.reverse()
print("\n")
print(good_places)
good_places.reverse()
print("\n")
print(good_places)
good_places.sort()
print("\n")
print(good_places)
good_places.sort(reverse = True)
print("\n")
print(good_places)
