hello: hello.cpp
	g++ -o hello hello.cpp -lncurses
window: window.cpp
	g++ -o window window.cpp -lncurses
attributes: attributes.cpp
	g++ -o attributes attributes.cpp -lncurses
attributes_example: attributes_example.cpp
	g++ -o attributes_example attributes_example.cpp -lncurses
getyx: getyx.cpp
	g++ -o getyx getyx.cpp -lncurses
input: input.cpp
	g++ -o input input.cpp -lncurses
menu: menu.cpp
	g++ -o menu menu.cpp -lncurses
refresh: refresh.cpp
	g++ -o refresh refresh.cpp -lncurses
input_mode: input_mode.cpp
	g++ -o input_mode input_mode.cpp -lncurses
attributes_data: attributes_data.cpp
	g++ -o attributes_data attributes_data.cpp -lncurses
chtype: chtype.cpp
	g++ -o chtype chtype.cpp -lncurses
detect: detect.cpp
	g++ -o detect detect.cpp -lncurses
chgat: chgat.cpp
	g++ -o chgat chgat.cpp -lncurses
clear: clear.cpp
	g++ -o clear clear.cpp -lncurses





